### ISSUE TITLE
Error in API with python

### ISSUE THREAD

**Issue by rickgds80** [dfirtrack/dfirtrack#163] opened 2022-05-10 18:59 UTC
I Try use the python API from example: https://github.com/dfirtrack/dfirtrack-api-python-client/blob/main/docs/ApiApi.md#list_cases
but when i execute this code, i have this error: 

  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 225, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.

Can you help me ?

**Comment by stuhli** [comment] 2022-05-10 21:39
@alexgoedeke or @n3x77 : can one of you take a look at it?

**Comment by n3x77** [comment] 2022-05-11 12:53
@rickgds80 which version of DFIRTrack are you using (version-nr and branch) and which version of the API client?

**Comment by rickgds80** [comment] 2022-05-11 14:18
I am using The last version of git project, i Just make a git clone, install docker, and genarete a token, but when i running The python API example i am take this error, i try in another API endpoints, but always The same error. I try in python3.9, python3.10.

**Comment by n3x77** [comment] 2022-05-11 14:41
@rickgds80  thanks for providing the versions. I'll try to check this within our lab and will respond to you.

**Comment by n3x77** [comment] 2022-05-12 13:40
@rickgds80, so I checked your problem with the current api client in python, and there are some aspects that you need to know. Maybe this was not documented clearly from our site and we will try to improve that. Nevertheless, the api feature is something we are currently working on, because in older versions of DFIRTrack we had some issues, so that not all relevant data was handled by the API in the correct format.

### DFIR-Track-Version and API-Client version

The first thing that is really important, is that the DFIRTrack Version must match to the version of the API client.
When Checking out the master branch you will be on DFIRTrack version 2.2.0, when using the dev-branch it will be version v2.4.10. 

To check the version of DFIRTrack you can just open DFIRTrack login and check the version on the start page:

![DFIRTrack Version](https://user-images.githubusercontent.com/20700780/168086310-a36bd865-3911-4e83-b2b9-6bb727140f59.png)

The API version can be checked when accessing the DFIRTrack URL `https://<yourserver>/api/openapi/

![API Version ](https://user-images.githubusercontent.com/20700780/168086302-74f30e2d-5a8e-4548-9d56-7f281134e804.png)

You can find the corresponding API clients within Github and a corresponding tag.
To install a specific version (e.g. 2.4.1) with pip just use the following command and use the tag:

```bash
pip install git+https://github.com/dfirtrack/dfirtrack-api-python-client.git@2.4.1   
```

### Working example within DFIRTrack Version from dev-branch and current api-client

It seems that in the version from the master branch, there are some issues in the API. So if you want
to use the API you should for now work with the develop branch of DFIRTrack. 

The second problem is, that were using the OpenAPI standard to generate the documentation that is provided
by the API client. Unfortunately this default documentation and code snippets are misleading. 
The problem is, that the configuration gots overwritten serveral times, therefore you have to uncomment
the other parts where the configuration is defined within the python snippet:

```python
import time
import dfirtrackapi_client
from dfirtrackapi_client.api import api_api
from dfirtrackapi_client.model.case import Case
from pprint import pprint
# Defining the host is optional and defaults to http://localhost
# See configuration.py for a list of all supported configuration parameters.
# Uncomment this and chose if you use the User-Password-Authentication or Bearer Auth
configuration = dfirtrackapi_client.Configuration(
    host = "http://localhost"
)

# The client must configure the authentication and authorization parameters
# in accordance with the API server security policy.
# Examples for each auth method are provided below, use the example that
# satisfies your auth use case.

# Configure HTTP basic authorization: basicAuth
# We define the configuration to use the host and User-Password-Based authentication
configuration = dfirtrackapi_client.Configuration(
    host = "https://<yourserver>"
    username = 'forensics',
    password = 'Passw0rd!'
)

# If you want to use Bearer authorization uncomment the following lines
# Configure Bearer authorization: bearerAuth
#configuration = dfirtrackapi_client.Configuration(
#    host = "https://<yourserver>"
#    access_token = 'YOUR_BEARER_TOKEN'
#)


# Enter a context with an instance of the API client
with dfirtrackapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = api_api.ApiApi(api_client)

    # example, this endpoint has no required or optional parameters
    try:
        api_response = api_instance.list_cases()
        pprint(api_response)
    except dfirtrackapi_client.ApiException as e:
        print("Exception when calling ApiApi->list_cases: %s\n" % e)
```

@rickgds80  I hope this helps and make some things clearer. Could you please try it with the current version of DFIRTrack and the corresponding API client. Everytime when we create a new tag in DFIRTRack the corresponding API-Client version will be automatically generated and can be found under the corresponding tag.

Please do not hesitate to ask if you have further questions.

**Comment by rickgds80** [comment] 2022-05-12 21:26
thank you very much for the clarifications.
The last branch is already 2.4, which is the only one available to download from git, when I uploaded the docker image that comes with the project, both dev or prod, the application's API version is 2.0, I don't know if the image is out of date. I managed to use curl + burp suite to see some backend requests, I tested it through the API documentation but without success, I'll wait for the bugs to be fixed. Thank you very much.

**Comment by n3x77** [comment] 2022-05-13 07:55
@rickgds80, so the current version **v.2.4.1 of DFIRTrack and the corresponding API client (v.2.4.1)** client should work fine together. 
It seems, that your docker containers use old cached images or volumes. Please make sure to delete them before running the new docker compose.

Best way is clone the DFIRTrack vom github using (git clone) and checkout the tag vor version 2.4.1, cleanup your old docker instances and rebuild it.

### Use Version 2.4.1 of DFIRTrack

1. Clone DFIRTrack vom the github repo
```bash
git clone https://github.com/dfirtrack/dfirtrack.git
```
2. Checkout tag 2.4.1 of DFIRTrack
```bash
git checkout tags/v2.4.1 -b <branch>
```
3. Install the corresping python api client using pip:
```bash
pip install git+https://github.com/dfirtrack/dfirtrack-api-python-client.git@2.4.1
````

4. Rebuild docker containers using docker compose
```bash
docker-compose build --force-recreate
```

**Comment by stuhli** [comment] 2022-06-02 15:11
Are there any remaining questions @rickgds80? Otherwise I will close this issue.

Lesson learned for us is to improve the documentation on this.

**Comment by rickgds80** [comment] 2022-06-03 07:46
Tank you so much, se can close this issue.

**Closed as completed** 2022-06-03 12:47 UTC
Labels: question
